name: Debug Auto promotion PR Creation for SQA
on:
      pull_request_target:
            types: [opened, synchronize, reopened]
jobs:
      validate_promotion_pr:
            runs-on: ubuntu-latest
            steps:
            - name: Debug event information
              run: |
                    echo "Event Action: ${{ github.event.action }}"
                    echo "Head Branch: ${{ github.event.pull_request.head.ref }}"
                    echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
                    echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
                    echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
                    echo "event: ${{ github.event }}"
                    echo "state: ${{ github.event.pull_request.state }}"
