name: Auto promotion PR validation for SQA
on:
      pull_request:
            types: [opened, synchronize, reopened]
            branches:
                  - SQA
            paths:
                  - 'force-app/**'
jobs:
      validate_promotion_pr:
            runs-on: ubuntu-latest
            if: "startsWith(github.event.pull_request.head.ref, 'gh-pipeline') && (github.event.action == 'opened' || github.event.action == 'synchronize')" 
            steps:
                - name: Checkout repository
                  uses: actions/checkout@v4
                  with:
                        fetch-depth: 0

                - name: List .cls files in the PR
                  run: |
                        # Use git diff to list files of the PR
                        files=$(git diff --name-only origin/SQA -- '*.cls')
                        
                        # Convert filenames to lowercase
                        lower_case_files=$(printf '%s\n' "$files" | tr '[:upper:]' '[:lower:]')
                        
                        # Filter files that contain "test"
                        filtered_files=()
                        while IFS= read -r file; do
                              if [[ "$file" == *"test"* ]]; then
                                    file=${file#force-app/main/default/classes/}
                                    file=${file%.cls}
                                    filtered_files+=("$file")
                              fi
                        done <<< "$lower_case_files"
                        
                        # Prepare a comma-separated list
                        filtered_file_list=$(IFS=,; echo "${filtered_files[*]}")
                        pr_body="${{ github.event.pull_request.body }}"
                        echo "$pr_body"
                        
                        apex_classes_from_pr_body=$(echo "$pr_body" | sed -n 's/.*::START_APEX_TEST::\(.*\)::END_APEX_TEST::.*/\1/p')
                        apex_classes_from_pr_body=${apex_classes_from_pr_body#comma separated list of test classes}
                        # Check if apex_classes_from_pr_body is empty
                        if [ -z "$apex_classes_from_pr_body" ]; then
                              echo "No .cls files containing 'test' found in the PR."
                        else
                              if [ -z "$filtered_file_list" ]; then
                                    filtered_file_list="$apex_classes_from_pr_body"
                              else
                                    filtered_file_list="$filtered_file_list,$apex_classes_from_pr_body"
                              fi
                        fi
                        # Print the result
                        echo "Filtered files: $filtered_file_list"
                        
                        # Set an output
                        if [ -z "$apex_classes_from_pr_body" ]; then
                              echo "No test class found"
                              echo "test_classes=$filtered_file_list" >> $GITHUB_ENV
                              echo "run_specified_test=false" >> $GITHUB_ENV
                        else
                              echo "test_classes=$filtered_file_list" >> $GITHUB_ENV
                              echo "run_specified_test=true" >> $GITHUB_ENV
                        fi
                - uses: patrykacc/sf-cli-setup@v1.1.0
                
                - name: CLI Health check
                  run: |
                      echo "CLI Installed succesfuly!"
                      sf -v
                      
                - name: Install SGD
                  run: |
                        echo y | sf plugins install sfdx-git-delta
                        sf plugins

                - name: 'Populate auth file with SFDX_URL secret of SQA org'
                  shell: bash
                  run: |
                        echo ${{ secrets.SFDX_SQA_URL }} > ./SFDX_SQA_URL.txt
                        
                - name: Authenticate to Salesforce
                  run: sf org login sfdx-url --sfdx-url-file ./SFDX_SQA_URL.txt --set-default --alias SQA

                - name: Verify Authentication
                  run: |
                        sf org display --target-org SQA

                - name: Generate Delta Package
                  run: |
                    # Get the base branch (main/master)
                    BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
                    HEAD_BRANCH="${{ github.event.pull_request.head.sha }}"
                    
                    echo "Generating delta package between $BASE_BRANCH and $HEAD_BRANCH"
                    
                    # Create delta directory
                    mkdir -p delta
                    
                    # Generate package.xml for changed components
                    sf sgd:source:delta \
                      --to $HEAD_BRANCH \
                      --from origin/$BASE_BRANCH \
                      --output-dir delta \
                      --generate-delta
            
                    # Display generated package.xml
                    echo "Generated package.xml:"
                    if [ -f "delta/package/package.xml" ]; then
                      cat delta/package/package.xml
                    else
                      echo "No package.xml generated"
                    fi
                    
                    # Check if there are any changes to deploy
                    if [ ! -f "delta/package/package.xml" ] || [ ! -s "delta/package/package.xml" ]; then
                      echo "No metadata changes detected"
                      echo "SKIP_DEPLOYMENT=true" >> $GITHUB_ENV
                    else
                      echo "SKIP_DEPLOYMENT=false" >> $GITHUB_ENV
                    fi
            
                # Validate deployment (Check Only)
                - name: Validate Deployment
                  id: validate_step # Assign an ID to this step to access its outputs
                  if: env.SKIP_DEPLOYMENT == 'false'
                  run: |
                    echo "Starting validation deployment..."
                    
                    # Run validation with test execution
                    if [ "$run_specified_test" = "true" ]; then
                          echo "Starting validation deployment with specified tests $test_classes"
                          sf project deploy validate --manifest delta/package/package.xml --target-org SQA --test-level RunSpecifiedTests --tests "$test_classes"--wait 30
                    else
                          echo "Starting validation deployment without test classes"
                          sf project deploy validate --manifest delta/package/package.xml --target-org SQA --wait 30
                    fi
                  env:
                    run_specified_test: ${{ env.run_specified_test }}
                    test_classes: ${{ env.test_classes }}
